.TH pohoda-bank-transaction-report 1 "" "version 1.8.5" "User Commands"
.SH NAME
pohoda-bank-transaction-report \- raiffeisenbank bank statement downloader for Stormware Pohoda
.SH SYNOPSIS
.B pohoda-bank-transaction-report
[\fIOPTIONS\fR]
.SH DESCRIPTION
raiffeisenbank bank statement downloader for Stormware Pohoda.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help and exit.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
