.TH raiffeisenbank-statements-sharepoint-checker 1 "" "version 1.8.1" "User Commands"
.SH NAME
raiffeisenbank-statements-sharepoint-checker \- raiffeisenbank bank statement downloader for Stormware Pohoda
.SH SYNOPSIS
.B raiffeisenbank-statements-sharepoint-checker
[\fIOPTIONS\fR]
.SH DESCRIPTION
raiffeisenbank bank statement downloader for Stormware Pohoda.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help and exit.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
