<?php

declare(strict_types=1);

/**
 * This file is part of the PohodaRaiffeisenbank package
 *
 * https://github.com/Spoje-NET/pohoda-raiffeisenbank
 *
 * (c) Spoje.Net IT s.r.o. <https://spojenet.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Pohoda\RaiffeisenBank;

use Pohoda\RaiffeisenBank\Statementor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 14:32:00.
 */
class StatementorTest extends \PHPUnit\Framework\TestCase
{
    protected Statementor $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Statementor(\Ease\Shared::cfg('ACCOUNT_NUMBER'), ['mock' => true]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::importXML
     */
    public function testimportXML(): void
    {
        $this->assertIsArray($this->object->importXML('../tests/194_2024_630804003_3780381_CZK_2024-11-06.xml'));
        $this->assertIsArray($this->object->importXML('../tests/testczk.xml'));
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::downloadXML
     */
    public function testdownloadXML(): void
    {
        $this->object->setScope('yesterday');
        $this->assertIsArray($this->object->downloadXML());
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::downloadPDF
     *
     * @todo   Implement testdownloadPDF().
     */
    public function testdownloadPDF(): void
    {
        $this->assertEquals('', $this->object->downloadPDF());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::importOnline
     *
     * @todo   Implement testimportOnline().
     */
    public function testimportOnline(): void
    {
        $this->assertEquals('', $this->object->importOnline());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::import
     *
     * @todo   Implement testimport().
     */
    public function testimport(): void
    {
        $this->assertEquals('', $this->object->import());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::entryToPohoda
     *
     * @todo   Implement testentryToPohoda().
     */
    public function testentryToPohoda(): void
    {
        $this->assertEquals('', $this->object->entryToPohoda());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::setScope
     */
    public function testsetScope(): void
    {
        $period = $this->object->setScope('last_month');
        $this->assertInstanceOf(\DatePeriod::class, $period);

        $since = \DateTime::createFromInterface($period->getStartDate());
        $until = \DateTime::createFromInterface($period->getEndDate());

        $this->assertSame((new \DateTime('first day of last month'))->format('Y-m-d'), $since->format('Y-m-d'));
        $this->assertSame((new \DateTime('last day of last month'))->format('Y-m-d'), $until->format('Y-m-d'));

        $period2 = $this->object->setScope('this_month');
        $since2 = \DateTime::createFromInterface($period2->getStartDate());
        $this->assertSame((new \DateTime('first day of this month'))->format('Y-m-d'), $since2->format('Y-m-d'));
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::getPdfStatements
     *
     * @todo   Implement testgetPdfStatements().
     */
    public function testgetPdfStatements(): void
    {
        $this->assertEquals('', $this->object->getPdfStatements());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::getXmlStatements
     *
     * @todo   Implement testgetXmlStatements().
     */
    public function testgetXmlStatements(): void
    {
        $this->assertEquals('', $this->object->getXmlStatements());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::statementFilename
     */
    public function testStatementFilename(): void
    {
        $this->assertSame(
            '194_2024_630804003_3780381_CZK_2024-11-06.pdf',
            Statementor::statementFilename('/tmp/194_2024_630804003_3780381_CZK_2024-11-06.pdf'),
        );
        $this->assertSame(
            '194_2024_630804003_3780381_CZK_2024-11-06.xml',
            Statementor::statementFilename('/tmp/194_2024_630804003_3780381_CZK_2024-11-06.xml'),
        );
        $this->assertSame(
            '007_2026_1000000001_9999999_CZK_2026-05-28.pdf',
            Statementor::statementFilename('/tmp/7_2026_1000000001_9999999_CZK_2026-05-28.pdf'),
        );
        $this->assertSame(
            '007_2026_1000000001_9999999_CZK_2026-05-28.xml',
            Statementor::statementFilename('/tmp/7_2026_1000000001_9999999_CZK_2026-05-28.xml'),
        );
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::filenameMatchesAccount
     */
    public function testFilenameMatchesAccount(): void
    {
        // NOTE: account numbers below are fictional example values only.
        // Correct account embedded in the statement filename.
        $this->assertTrue(
            Statementor::filenameMatchesAccount('151_2026_1000000001_9999999_CZK_2026-05-31.pdf', '1000000001'),
        );

        // Wrong-account (cross-attached) link: a record pointing at a sibling account's statement.
        $this->assertFalse(
            Statementor::filenameMatchesAccount('151_2026_1000000001_9999999_CZK_2026-05-31.pdf', '2000000002'),
        );

        // Account number with a slash is normalised to underscore.
        $this->assertTrue(
            Statementor::filenameMatchesAccount('001_1234567890_0100_9999999_CZK_2026-05-31.pdf', '1234567890/0100'),
        );

        // Empty / NULL DOC.Name (broken manual link) never matches.
        $this->assertFalse(Statementor::filenameMatchesAccount('', '1000000001'));

        // A manually attached local-file link does not match the account.
        $this->assertFalse(
            Statementor::filenameMatchesAccount('file:///C:/Users/Downloads/219_2025_1000000001.pdf', '2000000002'),
        );
    }
}
