<?php

declare(strict_types=1);

/**
 * This file is part of the PohodaRaiffeisenbank package
 *
 * https://github.com/Spoje-NET/pohoda-raiffeisenbank
 *
 * (c) Spoje.Net IT s.r.o. <https://spojenet.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Pohoda\RaiffeisenBank;

use Pohoda\RaiffeisenBank\Statementor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 14:32:00.
 */
class StatementorTest extends \PHPUnit\Framework\TestCase
{
    protected Statementor $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Statementor(\Ease\Shared::cfg('ACCOUNT_NUMBER'), ['mock' => true]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::importXML
     */
    public function testimportXML(): void
    {
        $this->assertIsArray($this->object->importXML('../tests/194_2024_630804003_3780381_CZK_2024-11-06.xml'));
        $this->assertIsArray($this->object->importXML('../tests/testczk.xml'));
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::downloadXML
     */
    public function testdownloadXML(): void
    {
        $this->object->setScope('yesterday');
        $this->assertIsArray($this->object->downloadXML());
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::downloadPDF
     *
     * @todo   Implement testdownloadPDF().
     */
    public function testdownloadPDF(): void
    {
        $this->assertEquals('', $this->object->downloadPDF());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::importOnline
     *
     * @todo   Implement testimportOnline().
     */
    public function testimportOnline(): void
    {
        $this->assertEquals('', $this->object->importOnline());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::import
     *
     * @todo   Implement testimport().
     */
    public function testimport(): void
    {
        $this->assertEquals('', $this->object->import());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::entryToPohoda
     *
     * @todo   Implement testentryToPohoda().
     */
    public function testentryToPohoda(): void
    {
        $this->assertEquals('', $this->object->entryToPohoda());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::setScope
     *
     * @todo   Implement testsetScope().
     */
    public function testsetScope(): void
    {
        $this->assertEquals('', $this->object->setScope());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::getPdfStatements
     *
     * @todo   Implement testgetPdfStatements().
     */
    public function testgetPdfStatements(): void
    {
        $this->assertEquals('', $this->object->getPdfStatements());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Statementor::getXmlStatements
     *
     * @todo   Implement testgetXmlStatements().
     */
    public function testgetXmlStatements(): void
    {
        $this->assertEquals('', $this->object->getXmlStatements());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
