<?php

declare(strict_types=1);

/**
 * This file is part of the PohodaRaiffeisenbank package
 *
 * https://github.com/Spoje-NET/pohoda-raiffeisenbank
 *
 * (c) Spoje.Net IT s.r.o. <https://spojenet.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Pohoda\RaiffeisenBank;

use Pohoda\RaiffeisenBank\CredentialGuard;
use Pohoda\RaiffeisenBank\Transactor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 14:31:59.
 */
class TransactorTest extends \PHPUnit\Framework\TestCase
{
    use CredentialGuard;

    protected Transactor $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Transactor(\Ease\Shared::cfg('ACCOUNT_NUMBER'), ['mock' => true]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::getTransactions
     *
     * @todo   Implement testgetTransactions().
     */
    public function testgetTransactions(): void
    {
        // getTransactions() calls exit() on an API failure (e.g. an expired test
        // certificate), which would kill the PHPUnit process rather than raise a
        // catchable error — so the credential precondition must be checked up front.
        $this->skipUnlessCertificateUsable();

        $this->object->setScope('today');
        $this->object->currency = 'CZK';

        $this->assertIsArray($this->object->getTransactions());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::import
     *
     * @todo   Implement testimport().
     */
    public function testimport(): void
    {
        // import() calls getTransactions(), which calls exit() on an API failure —
        // check credentials up front rather than relying on a catchable exception.
        $this->skipUnlessCertificateUsable();

        $this->object->setScope('today');
        $this->object->currency = 'CZK';

        $this->object->import();
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::takeTransactionData
     *
     * @todo   Implement testtakeTransactionData().
     */
    public function testtakeTransactionData(): void
    {
        $transactionData = json_decode(json_encode([
            'creditDebitIndication' => 'CRDT',
            'valueDate' => '2026-01-01',
            'entryReference' => 'TX123',
            'amount' => ['value' => 100, 'currency' => 'CZK'],
            'bankTransactionCode' => ['code' => 'PMNT'],
            'entryDetails' => [
                'transactionDetails' => [
                    'remittanceInformation' => [
                        'creditorReferenceInformation' => ['variable' => '123'],
                        'originatorMessage' => 'Test payment',
                    ],
                    'relatedParties' => [
                        'counterParty' => [
                            'name' => 'Test Counterparty',
                            'account' => ['accountNumber' => '1234567890'],
                            'organisationIdentification' => ['bankCode' => '0100'],
                        ],
                    ],
                ],
            ],
        ]));

        $this->object->takeTransactionData($transactionData);
        $this->assertSame('receipt', $this->object->getDataValue('bankType'));
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::setScope
     *
     * @todo   Implement testsetScope().
     */
    public function testsetScope(): void
    {
        $this->assertInstanceOf(\DatePeriod::class, $this->object->setScope('today'));
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
