<?php

declare(strict_types=1);

/**
 * This file is part of the PohodaRaiffeisenbank package
 *
 * https://github.com/Spoje-NET/pohoda-raiffeisenbank
 *
 * (c) Spoje.Net IT s.r.o. <https://spojenet.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Pohoda\RaiffeisenBank;

use Pohoda\RaiffeisenBank\Transactor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 14:31:59.
 */
class TransactorTest extends \PHPUnit\Framework\TestCase
{
    protected Transactor $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Transactor(\Ease\Shared::cfg('ACCOUNT_NUMBER'), ['mock' => true]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::getTransactions
     *
     * @todo   Implement testgetTransactions().
     */
    public function testgetTransactions(): void
    {
        $this->assertEquals('', $this->object->getTransactions());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::import
     *
     * @todo   Implement testimport().
     */
    public function testimport(): void
    {
        $this->assertEquals('', $this->object->import());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::takeTransactionData
     *
     * @todo   Implement testtakeTransactionData().
     */
    public function testtakeTransactionData(): void
    {
        $this->assertEquals('', $this->object->takeTransactionData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \Pohoda\RaiffeisenBank\Transactor::setScope
     *
     * @todo   Implement testsetScope().
     */
    public function testsetScope(): void
    {
        $this->assertEquals('', $this->object->setScope());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
